"builtin.module"() ({
  "llvm.mlir.global"() <{addr_space = 0 : i32, alignment = 4 : i64, constant, dso_local, global_type = !llvm.struct<(array<3 x struct<"class.llvm::EnumString", (array<1 x i16>, array<1 x i8>, i32)>>, array<29 x i8>)>, linkage = #llvm.linkage<external>, sym_name = "_ZZN4llvm20ELFCompactAttrParser15parseSubsectionEjE8TagNames", tls_mode = 0 : i64, unnamed_addr = 0 : i64, visibility_ = 1 : i64}> ({
    %0 = "llvm.mlir.constant"() <{value = "Tag_FileTag_SectionTag_Symbol"}> : () -> !llvm.array<29 x i8>
    %1 = "llvm.mlir.constant"() <{value = 3 : i32}> : () -> i32
    %2 = "llvm.mlir.constant"() <{value = "\0A"}> : () -> !llvm.array<1 x i8>
    %3 = "llvm.mlir.constant"() <{value = dense<27> : tensor<1xi16>}> : () -> !llvm.array<1 x i16>
    %4 = "llvm.mlir.undef"() : () -> !llvm.struct<"class.llvm::EnumString", (array<1 x i16>, array<1 x i8>, i32)>
    %5 = "llvm.insertvalue"(%4, %3) <{position = array<i64: 0>}> : (!llvm.struct<"class.llvm::EnumString", (array<1 x i16>, array<1 x i8>, i32)>, !llvm.array<1 x i16>) -> !llvm.struct<"class.llvm::EnumString", (array<1 x i16>, array<1 x i8>, i32)>
    %6 = "llvm.insertvalue"(%5, %2) <{position = array<i64: 1>}> : (!llvm.struct<"class.llvm::EnumString", (array<1 x i16>, array<1 x i8>, i32)>, !llvm.array<1 x i8>) -> !llvm.struct<"class.llvm::EnumString", (array<1 x i16>, array<1 x i8>, i32)>
    %7 = "llvm.insertvalue"(%6, %1) <{position = array<i64: 2>}> : (!llvm.struct<"class.llvm::EnumString", (array<1 x i16>, array<1 x i8>, i32)>, i32) -> !llvm.struct<"class.llvm::EnumString", (array<1 x i16>, array<1 x i8>, i32)>
    %8 = "llvm.mlir.constant"() <{value = 2 : i32}> : () -> i32
    %9 = "llvm.mlir.constant"() <{value = "\0B"}> : () -> !llvm.array<1 x i8>
    %10 = "llvm.mlir.constant"() <{value = dense<24> : tensor<1xi16>}> : () -> !llvm.array<1 x i16>
    %11 = "llvm.mlir.undef"() : () -> !llvm.struct<"class.llvm::EnumString", (array<1 x i16>, array<1 x i8>, i32)>
    %12 = "llvm.insertvalue"(%11, %10) <{position = array<i64: 0>}> : (!llvm.struct<"class.llvm::EnumString", (array<1 x i16>, array<1 x i8>, i32)>, !llvm.array<1 x i16>) -> !llvm.struct<"class.llvm::EnumString", (array<1 x i16>, array<1 x i8>, i32)>
    %13 = "llvm.insertvalue"(%12, %9) <{position = array<i64: 1>}> : (!llvm.struct<"class.llvm::EnumString", (array<1 x i16>, array<1 x i8>, i32)>, !llvm.array<1 x i8>) -> !llvm.struct<"class.llvm::EnumString", (array<1 x i16>, array<1 x i8>, i32)>
    %14 = "llvm.insertvalue"(%13, %8) <{position = array<i64: 2>}> : (!llvm.struct<"class.llvm::EnumString", (array<1 x i16>, array<1 x i8>, i32)>, i32) -> !llvm.struct<"class.llvm::EnumString", (array<1 x i16>, array<1 x i8>, i32)>
    %15 = "llvm.mlir.constant"() <{value = 1 : i32}> : () -> i32
    %16 = "llvm.mlir.constant"() <{value = "\08"}> : () -> !llvm.array<1 x i8>
    %17 = "llvm.mlir.undef"() : () -> !llvm.struct<"class.llvm::EnumString", (array<1 x i16>, array<1 x i8>, i32)>
    %18 = "llvm.insertvalue"(%17, %10) <{position = array<i64: 0>}> : (!llvm.struct<"class.llvm::EnumString", (array<1 x i16>, array<1 x i8>, i32)>, !llvm.array<1 x i16>) -> !llvm.struct<"class.llvm::EnumString", (array<1 x i16>, array<1 x i8>, i32)>
    %19 = "llvm.insertvalue"(%18, %16) <{position = array<i64: 1>}> : (!llvm.struct<"class.llvm::EnumString", (array<1 x i16>, array<1 x i8>, i32)>, !llvm.array<1 x i8>) -> !llvm.struct<"class.llvm::EnumString", (array<1 x i16>, array<1 x i8>, i32)>
    %20 = "llvm.insertvalue"(%19, %15) <{position = array<i64: 2>}> : (!llvm.struct<"class.llvm::EnumString", (array<1 x i16>, array<1 x i8>, i32)>, i32) -> !llvm.struct<"class.llvm::EnumString", (array<1 x i16>, array<1 x i8>, i32)>
    %21 = "llvm.mlir.undef"() : () -> !llvm.array<3 x struct<"class.llvm::EnumString", (array<1 x i16>, array<1 x i8>, i32)>>
    %22 = "llvm.insertvalue"(%21, %20) <{position = array<i64: 0>}> : (!llvm.array<3 x struct<"class.llvm::EnumString", (array<1 x i16>, array<1 x i8>, i32)>>, !llvm.struct<"class.llvm::EnumString", (array<1 x i16>, array<1 x i8>, i32)>) -> !llvm.array<3 x struct<"class.llvm::EnumString", (array<1 x i16>, array<1 x i8>, i32)>>
    %23 = "llvm.insertvalue"(%22, %14) <{position = array<i64: 1>}> : (!llvm.array<3 x struct<"class.llvm::EnumString", (array<1 x i16>, array<1 x i8>, i32)>>, !llvm.struct<"class.llvm::EnumString", (array<1 x i16>, array<1 x i8>, i32)>) -> !llvm.array<3 x struct<"class.llvm::EnumString", (array<1 x i16>, array<1 x i8>, i32)>>
    %24 = "llvm.insertvalue"(%23, %7) <{position = array<i64: 2>}> : (!llvm.array<3 x struct<"class.llvm::EnumString", (array<1 x i16>, array<1 x i8>, i32)>>, !llvm.struct<"class.llvm::EnumString", (array<1 x i16>, array<1 x i8>, i32)>) -> !llvm.array<3 x struct<"class.llvm::EnumString", (array<1 x i16>, array<1 x i8>, i32)>>
    %25 = "llvm.mlir.undef"() : () -> !llvm.struct<(array<3 x struct<"class.llvm::EnumString", (array<1 x i16>, array<1 x i8>, i32)>>, array<29 x i8>)>
    %26 = "llvm.insertvalue"(%25, %24) <{position = array<i64: 0>}> : (!llvm.struct<(array<3 x struct<"class.llvm::EnumString", (array<1 x i16>, array<1 x i8>, i32)>>, array<29 x i8>)>, !llvm.array<3 x struct<"class.llvm::EnumString", (array<1 x i16>, array<1 x i8>, i32)>>) -> !llvm.struct<(array<3 x struct<"class.llvm::EnumString", (array<1 x i16>, array<1 x i8>, i32)>>, array<29 x i8>)>
    %27 = "llvm.insertvalue"(%26, %0) <{position = array<i64: 1>}> : (!llvm.struct<(array<3 x struct<"class.llvm::EnumString", (array<1 x i16>, array<1 x i8>, i32)>>, array<29 x i8>)>, !llvm.array<29 x i8>) -> !llvm.struct<(array<3 x struct<"class.llvm::EnumString", (array<1 x i16>, array<1 x i8>, i32)>>, array<29 x i8>)>
    "llvm.return"(%27) : (!llvm.struct<(array<3 x struct<"class.llvm::EnumString", (array<1 x i16>, array<1 x i8>, i32)>>, array<29 x i8>)>) -> ()
  }) : () -> ()
  "llvm.module_flags"() <{flags = [#llvm.mlir.module_flag<error, "wchar_size", 4 : i32>, #llvm.mlir.module_flag<min, "PIC Level", 2 : i32>, #llvm.mlir.module_flag<max, "uwtable", 2 : i32>]}> : () -> ()
}) {dlti.dl_spec = #dlti.dl_spec<!llvm.ptr<270> = dense<32> : vector<4xi64>, !llvm.ptr<271> = dense<32> : vector<4xi64>, !llvm.ptr<272> = dense<64> : vector<4xi64>, i64 = dense<64> : vector<2xi64>, i128 = dense<128> : vector<2xi64>, f80 = dense<128> : vector<2xi64>, !llvm.ptr = dense<64> : vector<4xi64>, i1 = dense<8> : vector<2xi64>, i8 = dense<8> : vector<2xi64>, i16 = dense<16> : vector<2xi64>, i32 = dense<32> : vector<2xi64>, f16 = dense<16> : vector<2xi64>, f64 = dense<64> : vector<2xi64>, f128 = dense<128> : vector<2xi64>, "dlti.endianness" = "little", "dlti.mangling_mode" = "e", "dlti.legal_int_widths" = array<i32: 8, 16, 32, 64>, "dlti.stack_alignment" = 128 : i64>, llvm.ident = "Debian clang version 19.1.7 (3+b1)", llvm.module_asm = [], llvm.target_triple = "x86_64-pc-linux-gnu"} : () -> ()
